name: Python Package

on:
  push:
  pull_request:

jobs:
  flake8:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Poetry
        run: pip install poetry
      - name: Install project dependencies
        run: poetry install --no-interaction --no-root
      - name: Flake8
        uses: liskin/gh-problem-matcher-wrap@v1
        with:
          linters: flake8
          run: poetry run flake8 snecs/

  mypy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Poetry
        run: pip install poetry
      - name: Install project dependencies
        run: poetry install --no-interaction --no-root
      - name: MyPy
        uses: liskin/gh-problem-matcher-wrap@v1
        with:
          linters: mypy
          run: poetry run mypy --show-column-numbers

  isort:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install isort
        run: pip install isort
      - name: isort
        uses: liskin/gh-problem-matcher-wrap@v1
        with:
          linters: isort
          run: isort . --check

  black:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Black
        run: pip install black
      - name: Black
        run: black . --check --diff

  tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "pypy-3.6", "pypy-3.7"]
      fail-fast: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        run: pip install poetry
      - name: Install project dependencies
        run: poetry install --no-interaction --no-root
      - name: Run tests
        run: |
          poetry run python -m pytest -v --cov=snecs

  benchmarks:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ["3.9", "pypy-3.7"]
      fail-fast: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        run: pip install poetry
      - name: Install project dependencies
        run: poetry install --no-interaction --no-root
      - name: Run benchmarks
        run: poetry run ./run_benchmarks.sh
